window.SKILLHUB_SHARED = {
  ICON_SVG: {
    chartBars: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M4 20V10"/><path d="M10 20V4"/><path d="M16 20v-6"/><path d="M22 20v-9"/></svg>',
    penLine: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 19l7-7 3 3-7 7h-4v-3z"/><path d="M18 13l-1.5-7.5L2 2l3.5 14L13 18l5-5z"/></svg>',
    chat: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>',
    search: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>',
    clapper: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><rect x="2" y="7" width="20" height="12" rx="2"/><path d="M7 7V5a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v2"/><circle cx="12" cy="13" r="3"/></svg>',
    laptop: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 20h8"/><path d="M9 8h6M9 12h4"/></svg>',
    calendar: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18"/></svg>',
    mail: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M4 6h16v12H4z"/><path d="M22 7l-10 7L2 7"/></svg>',
    target: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2" fill="currentColor"/></svg>',
    globe: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15 15 0 0 1 0 20M12 2a15 15 0 0 0 0 20"/></svg>',
    dino: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 17c1-6 3-9 7-10-1-3 1-5 4-5 2 0 3 2 3 4 0 3-2 5-5 5-1 4-3 6-9 6z"/><circle cx="16" cy="8" r="1.2" fill="currentColor"/><path d="M4 14H2M6 12l-2-1"/></svg>',
    starBurst: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M12 2l1.8 5.5L19 9l-5.5 1.8L12 16l-1.5-5.2L5 9l5.2-1.5L12 2z"/></svg>',
    diamondG: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M12 3l7 8-7 10-7-10 7-8z"/></svg>',
    waves: '<svg class="ico-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M2 12c2-2 4-2 6 0s4 2 6 0 4-2 6 0"/><path d="M2 17c2-2 4-2 6 0s4 2 6 0 4-2 6 0"/></svg>',
  },
  DEPT_ORDER: [
    'all', 'dept_dinoai', 'dept_domestic', 'dept_overseas', 'dept_advisor', 'dept_ops', 'dept_sales',
    'dept_data_analytics', 'dept_product', 'dept_engineering', 'dept_qa', 'dept_research_edu',
    'dept_teacher', 'dept_finance', 'dept_hr', 'dept_study_tour', 'dept_picture_book',
  ],
  DEPT_LABELS: {
    all: '全部',
    dept_dinoai: 'DinoAI',
    dept_domestic: '国内市场',
    dept_overseas: '海外市场',
    dept_advisor: '班主任',
    dept_ops: '运营',
    dept_sales: '销售',
    dept_data_analytics: '数据分析',
    dept_product: '产品',
    dept_engineering: '研发',
    dept_qa: '测试',
    dept_research_edu: '教研',
    dept_teacher: '教师',
    dept_finance: '财务',
    dept_hr: '人力',
    dept_study_tour: '游学',
    dept_picture_book: '绘本馆',
  },
  SKILLS: [
    {
      id: 1,
      iconKey: 'chartBars',
      bg: 'linear-gradient(135deg,#F0984F,#E07A2F)',
      name: '数据分析助手',
      version: 'v2.1.4',
      desc: '上传 CSV/Excel，自动生成趋势分析、异常检测与可视化报告，支持自然语言提问。',
      tags: ['数据分析', 'Excel', '可视化'],
      creator: 'Baoyu',
      creatorColor: 'linear-gradient(135deg,#F0984F,#E07A2F)',
      contribs: [{ c: '#2EB8D9', t: 'Z' }, { c: '#7C6FDB', t: 'L' }],
      uses: '8.4k',
      likes: 342,
      cat: 'data',
      depts: ['dept_dinoai', 'dept_data_analytics', 'dept_product', 'dept_ops'],
      desc_long: '上传任何 CSV 或 Excel 文件后，本技能可自动识别字段类型，计算描述性统计量，检测时序趋势与异常数据点，并生成可直接发送的可视化报告。支持用中文自然语言追问，例如「上周比上上周下降了多少」。',
      versions: [
        { v: 'v2.1.4', date: '2025-06-01', notes: '修复空列处理 bug，提升大文件性能 30%' },
        { v: 'v2.1.0', date: '2025-05-15', notes: '新增异常检测模块，支持 3-sigma 和 IQR 方法' },
        { v: 'v2.0.0', date: '2025-04-10', notes: '重构提示词结构，支持多表关联分析' },
      ],
      videoLabel: '演示：Excel 数据分析 · 3:12',
    },
    {
      id: 2,
      iconKey: 'penLine',
      bg: 'linear-gradient(135deg,#7C6FDB,#6558C4)',
      name: '日报周报生成器',
      version: 'v1.3.0',
      desc: '根据工作日志或简单描述，自动格式化为标准日报/周报，一键复制发飞书/钉钉。',
      tags: ['内容创作', '效率', '报告'],
      creator: '小雨',
      creatorColor: 'linear-gradient(135deg,#7C6FDB,#6558C4)',
      contribs: [{ c: '#F0984F', t: 'B' }, { c: '#3AAF6E', t: 'J' }, { c: '#2EB8D9', t: 'Z' }],
      uses: '5.2k',
      likes: 218,
      cat: 'content',
      depts: ['dept_dinoai', 'dept_picture_book', 'dept_ops', 'dept_hr', 'dept_finance'],
      desc_long: '输入你今天做了什么（随意格式），技能自动整理为规范的日报结构：今日完成、明日计划、需要协调。支持钉钉卡片、飞书文档、纯文本三种输出格式，可设置个人风格偏好。',
      versions: [
        { v: 'v1.3.0', date: '2025-06-03', notes: '新增飞书卡片输出格式' },
        { v: 'v1.2.0', date: '2025-05-20', notes: '支持周报模式，自动汇总当周日报' },
      ],
      videoLabel: '演示：从碎片笔记到规范日报 · 1:45',
    },
    {
      id: 3,
      iconKey: 'chat',
      bg: 'linear-gradient(135deg,#2EB8D9,#1A9DC0)',
      name: '销售话术教练',
      version: 'v3.0.1',
      desc: '分析销售通话录音或文字记录，从邀约、诊脉、异议处理维度给出专业反馈。',
      tags: ['销售支持', '分析', '培训'],
      creator: 'Lily',
      creatorColor: 'linear-gradient(135deg,#2EB8D9,#1A9DC0)',
      contribs: [{ c: '#F0984F', t: 'M' }, { c: '#7C6FDB', t: 'K' }],
      uses: '3.8k',
      likes: 156,
      cat: 'sales',
      depts: ['dept_dinoai', 'dept_sales', 'dept_study_tour', 'dept_domestic', 'dept_overseas'],
      desc_long: '基于销冠实战心法，对销售对话从七个维度评分：开场白质量、需求挖掘深度、产品匹配度、异议处理能力、逼单时机、情绪管理、后续跟进计划。提供具体改进建议和示范话术。',
      versions: [
        { v: 'v3.0.1', date: '2025-06-02', notes: '热修复：修复中文引号识别问题' },
        { v: 'v3.0.0', date: '2025-05-28', notes: '全面重构评分体系，新增情绪管理维度' },
        { v: 'v2.5.0', date: '2025-04-30', notes: '支持音频文件自动转录后分析' },
      ],
      videoLabel: '演示：通话录音分析 · 2:58',
    },
    {
      id: 4,
      iconKey: 'search',
      bg: 'linear-gradient(135deg,#3AAF6E,#2D8F58)',
      name: '竞品调研摘要',
      version: 'v1.1.2',
      desc: '输入竞品名称或 URL，自动抓取公开信息，生成结构化竞品分析报告。',
      tags: ['调研洞察', '竞品', '报告'],
      creator: 'Jason',
      creatorColor: 'linear-gradient(135deg,#3AAF6E,#2D8F58)',
      contribs: [{ c: '#F0984F', t: 'A' }],
      uses: '2.1k',
      likes: 89,
      cat: 'research',
      depts: ['dept_study_tour', 'dept_overseas', 'dept_product', 'dept_data_analytics'],
      desc_long: '使用浏览器 CDP 和搜索工具抓取目标竞品的官网、AppStore 评价、新闻报道、招聘信息等公开数据，自动整合为：产品定位、核心功能、用户反馈、近期动态、与我们的对比五个模块。',
      versions: [
        { v: 'v1.1.2', date: '2025-06-04', notes: '改善 App Store 评价抓取稳定性' },
        { v: 'v1.1.0', date: '2025-05-18', notes: '新增 LinkedIn 招聘信息维度' },
      ],
      videoLabel: '演示：竞品一键调研 · 2:05',
    },
    {
      id: 5,
      iconKey: 'clapper',
      bg: 'linear-gradient(135deg,#E07A2F,#C96020)',
      name: 'YouTube 智能剪辑',
      version: 'v2.2.0',
      desc: '下载视频和字幕，AI 分析生成章节，一键剪辑片段并烧录双语字幕。',
      tags: ['媒体处理', '视频', '字幕'],
      creator: 'Baoyu',
      creatorColor: 'linear-gradient(135deg,#F0984F,#E07A2F)',
      contribs: [{ c: '#2EB8D9', t: 'Z' }, { c: '#3AAF6E', t: 'J' }],
      uses: '4.7k',
      likes: 201,
      cat: 'media',
      depts: ['dept_picture_book', 'dept_study_tour', 'dept_teacher', 'dept_research_edu', 'dept_advisor'],
      desc_long: '输入 YouTube URL，技能自动下载视频与字幕，AI 分析内容结构生成精细章节（分钟级），用户选择目标片段后自动剪辑、将字幕翻译为中英双语、烧录字幕到视频，并输出总结文案。',
      versions: [
        { v: 'v2.2.0', date: '2025-06-01', notes: '支持批量下载，新增字幕样式选项' },
        { v: 'v2.1.0', date: '2025-05-10', notes: 'AI 章节分析精度提升' },
        { v: 'v2.0.0', date: '2025-04-20', notes: '重构为双语字幕烧录流程' },
      ],
      videoLabel: '演示：视频剪辑全流程 · 3:40',
    },
    {
      id: 6,
      iconKey: 'laptop',
      bg: 'linear-gradient(135deg,#6558C4,#4E43A8)',
      name: '代码 Review 助手',
      version: 'v1.4.1',
      desc: '分析 Git diff 或代码片段，从安全性、性能、可读性、测试覆盖四个维度给出 Review 意见。',
      tags: ['代码工具', 'Review', '质量'],
      creator: 'Alex',
      creatorColor: 'linear-gradient(135deg,#6558C4,#4E43A8)',
      contribs: [{ c: '#F0984F', t: 'B' }, { c: '#2EB8D9', t: 'Z' }],
      uses: '6.3k',
      likes: 287,
      cat: 'code',
      depts: ['dept_dinoai', 'dept_engineering', 'dept_qa', 'dept_product'],
      desc_long: '粘贴 Git diff 或代码片段，技能系统性地检查：潜在安全漏洞（SQL注入、XSS等）、性能瓶颈（N+1查询、无效循环）、可读性问题（命名、复杂度）、缺失的测试用例，并给出具体的修改建议和改进示例。',
      versions: [
        { v: 'v1.4.1', date: '2025-06-03', notes: '热修复 Python 类型提示解析' },
        { v: 'v1.4.0', date: '2025-05-25', notes: '新增 TypeScript/Rust 语言支持' },
        { v: 'v1.3.0', date: '2025-05-01', notes: '加入安全漏洞专项检测模块' },
      ],
      videoLabel: '演示：PR Review 全流程 · 2:22',
    },
  ],
  COMMENTS_DATA: [
    { name: '张小明', color: 'linear-gradient(135deg,#F0984F,#E07A2F)', initial: '张', time: '3小时前', text: '真的超好用！导出的报告直接给老板看，省了我半天时间。' },
    { name: 'Lily Chen', color: 'linear-gradient(135deg,#2EB8D9,#1A9DC0)', initial: 'L', time: '1天前', text: '数据量大的时候会稍微慢一点，但分析质量很高，比我自己写的好多了。' },
    { name: '王运营', color: 'linear-gradient(135deg,#7C6FDB,#6558C4)', initial: '王', time: '2天前', text: '建议增加月报模式，其他都很完美！' },
  ],
};
